version: "3.8"

services:
  sqldb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
        - 1433:1433
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=HS1212hs
    networks:
        - employeesapi
    volumes:
        - D:\Amin-Ray\WebAPI\Employees\SQLBackup:/var/opt/mssql/data
  
  webapi:
    image: hosseinsedghian/employeesapi:v4
    ports:
        - 8080:8080
    environment:
        - DB_SERVER=sqldb
        - DB_NAME=Employees
        - USER_ID=sa
        - PASSWORD=HS1212hs
    networks:
        - employeesapi
    depends_on:
        - sqldb
    restart: always
networks:
  employeesapi:
    driver: bridge
