version: "3.8"
services:
  sqldb:
   image: mcr.microsoft.com/mssql/server:2019-latest
   container_name: 'sqldb'
   command: bash -c "chown 10001:0 /var/opt/sqlserver/data && chown 10001:0 /var/opt/sqlserver/log"
   expose:
   - '1433' 
   environment:
   - ACCEPT_EULA=Y
   - SA_PASSWORD=HS1212hs
   - MSSQL_DATA_DIR=/var/opt/sqlserver/data
   - MSSQL_LOG_DIR=/var/opt/sqlserver/log
   - MSSQL_BACKUP_DIR=/var/opt/sqlserver/backup    
   networks:
    - my-main-net 
   volumes:
    - sqlsystem:/var/opt/mssql/
    - sqldata:/var/opt/sqlserver/data
    - sqllog:/var/opt/sqlserver/log
    - sqlbackup:/var/opt/sqlserver/backup
networks:
  my-main-net:
    external: true
volumes:
  sqlsystem:
  sqldata:
  sqllog:
  sqlbackup:  