version: "3.8"
services:
  sqldb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    expose:
        - '1433'
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=HS1212hs
    networks:
        - my-main-net
    volumes:
        - /home/hosseinsedghian/employees/sql/data:/var/opt/mssql/data
  
  webapi:
    image: hosseinsedghian/employeesapi:v4
    expose:
        - '12080'
    environment:
        - DB_SERVER=sqldb
        - DB_NAME=Employees
        - USER_ID=sa
        - PASSWORD=HS1212hs
    networks:
        - my-main-net
    depends_on:
        - sqldb
    restart: always
